SCOWebApp/Controllers/ShoppingCartController.cs
using Microsoft.AspNetCore.Mvc;
using SCOWebApp.Models;
using SCOWebApp.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SCOWebApp.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly ITripRepository _tripRepository;
        private readonly ShoppingCart _shoppingCart;

        public ShoppingCartController(ITripRepository tripRepository, ShoppingCart shoppingCart) //constructor injection
        {
            _tripRepository = tripRepository;
            _shoppingCart = shoppingCart;
        } //allows us to get controller
        public IActionResult Index()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var shoppingCartViewModel = new ShoppingCartViewModel
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };
            return View(shoppingCartViewModel);
        }

        public RedirectToActionResult AddToShoppingCart(int tripId)
        {
            var selectedTrip = _tripRepository.AllTrips.FirstOrDefault(t => t.TripId == tripId);

            if(selectedTrip != null)
            {
                _shoppingCart.AddToCart(selectedTrip, 1);
            }
            return RedirectToAction("Index");
        }

        public RedirectToActionResult RemoveFromShoppingCart(int tripId)
        {
            var selectedTrip = _tripRepository.AllTrips.FirstOrDefault(t => t.TripId == tripId);

            if(selectedTrip != null)
            {
                _shoppingCart.RemoveFromCart(selectedTrip);
            }
            return RedirectToAction("Index");
        }
    }
}

SCOWebApp/Controllers/TripController.cs
using Microsoft.AspNetCore.Mvc;
using SCOWebApp.Models;
using SCOWebApp.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SCOWebApp.Controllers
{
    public class TripController : Controller
    {
        private readonly ITripRepository _tripRepository;
        private readonly ICategoryRepository _categoryRepository;

        public TripController(ITripRepository tripRepository, ICategoryRepository categoryRepository) //dependency injection since registered in startup.cs
        {
            //giving controller access to models
            _tripRepository = tripRepository;
            _categoryRepository = categoryRepository;
        }

        public ViewResult List()
        {
            TripsListViewModel tripsListViewModel = new TripsListViewModel();
            tripsListViewModel.Trips = _tripRepository.AllTrips;

            tripsListViewModel.CurrentCategory = "Camping";
            return View(tripsListViewModel);
        }

        public IActionResult Details(int id) //for page navigation to each trip
        {
            var trip = _tripRepository.GetTripById(id);
            if(trip == null)
            {
                return NotFound(); //404 error
            }
            return View(trip); //returns a view with the corresponding id as a parameter
        }
    }
}

SCOWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro">
    <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    <link href="~/content/site.css" rel="stylesheet" />
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-controller="Trip" asp-action="List">Trips</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <p class="lead">
                    <img class="img-responsive" alt="SCO Web App'" src="~/images/scologo.png" />
                </p>
            </div>
            <div class="col-md-9">
                @RenderBody()
            </div>
        </div>
    </div>
</body>
</html>

SCOWebApp/Views/Shared/_Slideshow.cshtml
<div class="row carousel-holder">
    <div class="col-md-12">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2" class="active"></li>
            </ol>
            <div class="carousel-inner">
                <div class="item active">
                    <img class="slide-image" src="~/images/carousel1.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/images/carousel2.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/images/carousel3.jpg" alt="">
                </div>
            </div>
            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>
    </div>
</div>

SCOWebApp/Views/Shared/_TripCard.cshtml
@model Trip

<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
        <img src="@Model.ImageThumbnailUrl" alt="">
        <div class="caption">
            <h3 class=" ="pull-right">@Model.Price.ToString("c")</h3>
            <h3>
                <a asp-controller="Trip" asp-action="Details" asp-route-id="@Model.TripId">@Model.Name</a>
            </h3>
            <p>@Model.ShortDescription</p>
        </div>
        <div class="addToCart">
            <p class="button">
                <a class="btn btn-primary" asp-controller="ShoppingCart" asp-action="AddToShoppingCart"
                   asp-route-tripId="@Model.TripId">Add to cart</a>
            </p>
        </div>
    </div>
</div>